### ISSUE TITLE
Support for animated cursor?

### ISSUE THREAD

**Issue by Michael-Tanzer** [aleios/gw2-cursoroverride#3]
Back in the days of YoloMouse, I had made an animated cursor that flashed different colours to make it even easier to see. Is this function supported here? Any clue on where to look in the source code to implement it?

The cursors would just need to be 2 images alternating every T given time

**Comment by aleios** [comment]
So it doesn't support it as is. But the existing functions could be leveraged to do it.

Where to start would be on line 201 of main.cpp. Instead of just 'myCursor' I'd make an array of 2 or more cursors. Load them using createCursor for each and could use a timer inside the dll thread to alternate the index of the current cursor after an interval.

I might give this a look into at some point, maybe even just straight up support for multiple cursors. Just really busy at the moment unfortunately.

**Comment by Michael-Tanzer** [comment]
Thank you for the replies.
I'm happy to give it a go, although I am not the best at neither windows programming nor C++.
If I manage I'll open a PR for you to have a look.

**Comment by aleios** [comment]
I think I figured it out. Is your animated cursor a '.ani' file? If so you can use this patched version. It'll load cursor.ani instead of .png.

Whole project could do with a rework to support any cursor file to be honest.

[curoverride-2.zip](https://github.com/aleios/gw2-cursoroverride/files/12546370/curoverride-2.zip)

**Comment by Michael-Tanzer** [comment]
Oh wow thank you! I'll test it later today!
